# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - docs/*
    - azure-pipelines-mkdocs.yaml
    - mkdocs.yml
    - requirements.txt

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'

- script: |
   pip install --upgrade pip setuptools wheel
   pip install -r requirements.txt
   mkdocs --verbose gh-deploy
  displayName: Install the MkDocs + Publish to GitHub Pages
